### PR TITLE
Fixes #33 Incorrect code generated for property Map<String, Bar>

### LINKED ISSUE #33: Incorrect code generated for property Map<String, Bar>
below the generator generates code for property Foo#bars as if it were 

    Map<String, String> 

rather than its actual type

    Map<String, Bar> 

(also builders for Bar are not created as expected)

    import java.util.Map;
    
    public class Foo {
        private Map<String, Bar> bars;
        public Map<String, Bar> getBars() {
            return bars;
        }
        public void setBars(Map<String, Bar> bars) {
            this.bars = bars;
        }
    }
    public class Bar {
        public String thing;
        public String getThing() {
            return thing;
        }
        public void setThing(String thing) {
            this.thing = thing;
        }
    }

main

    public class GenerateV1Builders {
        
        final private static String DEFAULT_OUTPUT_DIRECTORY = "src/test/java";
        final private static String DEFAULT_BUILDER_PACKAGE = "com.blah.generatedbuilders";
    
        public static void main(String[] args) {    
            generateBuildersFor(Foo.class);
        }
    
        private static void generateBuildersFor(Class<?> clazz) {
    
            BuilderGenerator bg = new BuilderGenerator(clazz);
            bg.setOutputDirectory(DEFAULT_OUTPUT_DIRECTORY);
            bg.setBuilderPackage(DEFAULT_BUILDER_PACKAGE);
            bg.setGenerationGap(true);
            bg.generateBuilders();
        }
    }

generates 

     public class FooBaseBuilder<T extends com.blah.generatedbuilders.FooBaseBuilder<T>> {
        
        private com.blah.model.Foo target = new com.blah.model.Foo();
        
        public FooBaseBuilder() {}
        
        public T withBars(java.util.Map<java.lang.String, java.lang.String> bars) {    // WRONG
            getTarget().setBars(bars);
            return (T) this;
        }
        
        protected com.blah.model.Foo getTarget() {
            return target;
        }
        
        public com.blah.model.Foo build() {
            return getTarget();
        }
    }

does not generate Bar builders

### PR DESCRIPTION
**Pull request by azzoti**
In BuilderGeneratorIT#readFiles  I added line = line.trim(); which allowed the tests to pass on machine at work, otherwise I got space differences.

I also added test BuilderGeneratorIT#beanWithCollectionAlsoGeneratesBuilderForGenericType to check that Address#List<House> generates HouseBuilder class which is nothing to do with the issue #33.

### CODE REVIEW

**Comment by uglycustard** [comment]
You've added the deleteGeneratedFiles method to FileUtils which is hard coded to the integration test folder - but FileUtils is in main and part of the application.  I think this delete method which only appears to be invoked from the IT should be moved to a private method in the IT class.

**Comment by azzoti** [comment]
done I think - blimey this git stuff is complicated!

**Comment by uglycustard** [comment]
Cool, I'm away this weekend but will pull it in on Sunday and release it. Cheers.

Sent from Yahoo Mail on Android

**Comment by uglycustard** [comment]
Release 0.0.21

**Pull request merged**
